### PR TITLE
updated xUnitContext to also support netstandard2.1

### PR DESCRIPTION
**Pull request by nielsNocore**
updated project to also support netstandard2.1

### CODE REVIEW

**Comment by SimonCropp** [comment]
why do u need this? u cant run tests on netstandard

**Comment by nielsNocore** [comment]
we made a libary used in different projects, running .net 6 or .net 8 zo i would like to build te package in net standard2.1. 
but a this moment i can not update XunitContext packages because it does not support net standard 2.1

**Comment by bartelink** [comment]
net6.0 supports .net 6 and .net 8 ?
netstandard2.1 is and was a very low usage thing...

**Comment by SimonCropp** [comment]
@nielsNocore as @bartelink pointed out, you can target net6 to achieve the same thing

**Comment by nielsNocore** [comment]
oke, i was not aware that was possible, ik will have a look at it. thank you!

**Pull request closed without merging**
