### PR TITLE
Fix test exception relying on DeclaringType not being null

### PR DESCRIPTION
**Pull request by gdoron**

### CODE REVIEW

**Comment by SimonCropp** [comment]
can u add a test

**Comment by gdoron** [comment]
@SimonCropp , any reason why `TestException_Sync` and `TestException_Async` are in comments?
Where should I write the UT in?

**Comment by gdoron** [comment]
And it seems it's not just lambda, it's for when the property is being generated with reflection, like with my case by auto mapper.
https://stackoverflow.com/a/35266142

**Comment by gdoron** [comment]
@SimonCropp any chance you can merge this?
It's really not easy writing a UT for this, but for sure considering null there is completely safe and solves issue when using automapper or EF.

Thanks!

**Pull request merged**
